name: base
channels:
  - defaults
dependencies:
  - _anaconda_depends=2020.07
  - _ipyw_jlab_nb_ext_conf=0.1.0
  - alabaster=0.7.12
  - anaconda=custom
  - anaconda-client=1.7.2
  - anaconda-navigator=1.10.0
  - anaconda-project=0.9.1
  - appdirs=1.4.4
  - argh=0.26.2
  - argon2-cffi=20.1.0
  - asn1crypto=1.4.0
  - astroid=2.4.2
  - astropy=4.2
  - async_generator=1.10
  - atomicwrites=1.4.0
  - attrs=20.3.0
  - autopep8=1.5.4
  - babel=2.9.0
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.1
  - backports.shutil_get_terminal_size=1.0.0
  - backports.tempfile=1.0
  - backports.weakref=1.0.post1
  - bcrypt=3.2.0
  - beautifulsoup4=4.9.3
  - bitarray=1.6.3
  - bkcharts=0.2
  - black=19.10b0
  - blas=1.0
  - bleach=3.2.3
  - blosc=1.20.1
  - bokeh=2.2.3
  - boto=2.49.0
  - bottleneck=1.3.2
  - brotli=1.0.9
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - ca-certificates=2021.1.19
  - certifi=2020.12.5
  - cffi=1.14.4
  - chardet=4.0.0
  - charls=2.1.0
  - click=7.1.2
  - cloudpickle=1.6.0
  - clyent=1.2.2
  - colorama=0.4.4
  - conda=4.9.2
  - conda-build=3.20.5
  - conda-env=2.6.0
  - conda-package-handling=1.7.2
  - conda-verify=3.4.2
  - console_shortcut=0.1.1
  - contextlib2=0.6.0.post1
  - cryptography=3.3.1
  - curl=7.71.1
  - cycler=0.10.0
  - cython=0.29.21
  - cytoolz=0.11.0
  - dask=2021.1.1
  - dask-core=2021.1.1
  - decorator=4.4.2
  - defusedxml=0.6.0
  - diff-match-patch=20200713
  - distributed=2021.1.1
  - docutils=0.16
  - entrypoints=0.3
  - et_xmlfile=1.0.1
  - fastcache=1.1.0
  - filelock=3.0.12
  - flake8=3.8.4
  - flask=1.1.2
  - freetype=2.10.4
  - fsspec=0.8.3
  - future=0.18.2
  - get_terminal_size=1.0.0
  - gevent=21.1.1
  - giflib=5.2.1
  - glob2=0.7
  - gmpy2=2.0.8
  - greenlet=1.0.0
  - h5py=2.10.0
  - hdf5=1.10.4
  - heapdict=1.0.1
  - html5lib=1.1
  - icu=58.2
  - idna=2.10
  - imageio=2.9.0
  - imagesize=1.2.0
  - importlib-metadata=2.0.0
  - importlib_metadata=2.0.0
  - iniconfig=1.1.1
  - intel-openmp=2020.2
  - intervaltree=3.1.0
  - ipykernel=5.3.4
  - ipython=7.19.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.6.3
  - isort=5.6.4
  - itsdangerous=1.1.0
  - jdcal=1.4.1
  - jedi=0.17.2
  - jinja2=2.11.2
  - joblib=1.0.0
  - jpeg=9b
  - json5=0.9.5
  - jsonschema=3.2.0
  - jupyter=1.0.0
  - jupyter_client=6.1.7
  - jupyter_console=6.2.0
  - jupyter_core=4.7.0
  - jupyterlab=2.2.6
  - jupyterlab_pygments=0.1.2
  - jupyterlab_server=1.2.0
  - jupyterlab_widgets=1.0.0
  - keyring=22.0.1
  - kiwisolver=1.3.0
  - krb5=1.18.2
  - lazy-object-proxy=1.4.3
  - lcms2=2.11
  - lerc=2.2.1
  - libaec=1.0.4
  - libarchive=3.4.2
  - libcurl=7.71.1
  - libdeflate=1.7
  - libiconv=1.15
  - liblief=0.10.1
  - libllvm9=9.0.1
  - libpng=1.6.37
  - libsodium=1.0.18
  - libspatialindex=1.9.3
  - libssh2=1.9.0
  - libtiff=4.1.0
  - libxml2=2.9.10
  - libxslt=1.1.34
  - libzopfli=1.0.3
  - llvmlite=0.34.0
  - locket=0.2.1
  - lxml=4.6.2
  - lz4-c=1.9.3
  - lzo=2.10
  - markupsafe=1.1.1
  - matplotlib=3.3.2
  - matplotlib-base=3.3.2
  - mccabe=0.6.1
  - mistune=0.8.4
  - mkl=2020.2
  - mkl-service=2.3.0
  - mkl_fft=1.2.0
  - mkl_random=1.1.1
  - mock=4.0.3
  - more-itertools=8.6.0
  - mpc=1.1.0
  - mpfr=4.0.2
  - mpir=3.0.0
  - mpmath=1.1.0
  - msgpack-python=1.0.1
  - multipledispatch=0.6.0
  - mypy_extensions=0.4.3
  - navigator-updater=0.2.1
  - nbclient=0.5.1
  - nbconvert=6.0.7
  - nbformat=5.1.2
  - nest-asyncio=1.4.2
  - networkx=2.5
  - nltk=3.5
  - nose=1.3.7
  - notebook=6.2.0
  - numba=0.51.2
  - numexpr=2.7.2
  - numpy=1.19.2
  - numpy-base=1.19.2
  - numpydoc=1.1.0
  - olefile=0.46
  - openjpeg=2.3.0
  - openpyxl=3.0.6
  - openssl=1.1.1i
  - packaging=20.9
  - pandas=1.2.1
  - pandoc=2.11
  - pandocfilters=1.4.3
  - paramiko=2.7.2
  - parso=0.7.0
  - partd=1.1.0
  - path=15.1.0
  - path.py=12.5.0
  - pathlib2=2.3.5
  - pathspec=0.7.0
  - pathtools=0.1.2
  - patsy=0.5.1
  - pep8=1.7.1
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=8.1.0
  - pip=20.3.3
  - pkginfo=1.7.0
  - plotly=4.14.3
  - pluggy=0.13.1
  - ply=3.11
  - prometheus_client=0.9.0
  - prompt-toolkit=3.0.8
  - prompt_toolkit=3.0.8
  - psutil=5.7.2
  - ptyprocess=0.7.0
  - py=1.10.0
  - py-lief=0.10.1
  - pycodestyle=2.6.0
  - pycosat=0.6.3
  - pycparser=2.20
  - pycurl=7.43.0.6
  - pydocstyle=5.1.1
  - pyerfa=1.7.1.1
  - pyflakes=2.2.0
  - pygments=2.7.4
  - pylint=2.6.0
  - pyls-black=0.4.6
  - pynacl=1.4.0
  - pyodbc=4.0.30
  - pyopenssl=20.0.1
  - pyparsing=2.4.7
  - pyqt=5.9.2
  - pyrsistent=0.17.3
  - pysocks=1.7.1
  - pytables=3.6.1
  - pytest=6.2.2
  - python=3.8.5
  - python-dateutil=2.8.1
  - python-jsonrpc-server=0.4.0
  - python-language-server=0.36.2
  - python-libarchive-c=2.9
  - pytz=2020.5
  - pywavelets=1.1.1
  - pyyaml=5.4.1
  - pyzmq=20.0.0
  - qdarkstyle=2.8.1
  - qt=5.9.7
  - qtawesome=1.0.1
  - qtconsole=4.7.7
  - qtpy=1.9.0
  - regex=2020.11.13
  - requests=2.25.1
  - retrying=1.3.3
  - rope=0.18.0
  - rtree=0.9.4
  - ruamel_yaml=0.15.87
  - scikit-image=0.17.2
  - scikit-learn=0.23.2
  - scipy=1.5.2
  - seaborn=0.11.1
  - send2trash=1.5.0
  - setuptools=52.0.0
  - simplegeneric=0.8.1
  - singledispatch=3.4.0.3
  - sip=4.19.13
  - six=1.15.0
  - snappy=1.1.8
  - snowballstemmer=2.1.0
  - sortedcollections=2.1.0
  - sortedcontainers=2.3.0
  - soupsieve=2.1
  - sphinx=3.4.3
  - sphinxcontrib=1.0
  - sphinxcontrib-applehelp=1.0.2
  - sphinxcontrib-devhelp=1.0.2
  - sphinxcontrib-htmlhelp=1.0.3
  - sphinxcontrib-jsmath=1.0.1
  - sphinxcontrib-qthelp=1.0.3
  - sphinxcontrib-serializinghtml=1.1.4
  - sphinxcontrib-websupport=1.2.4
  - sqlalchemy=1.3.21
  - sqlite=3.33.0
  - statsmodels=0.12.1
  - sympy=1.7.1
  - tbb=2020.3
  - tblib=1.7.0
  - terminado=0.9.2
  - testpath=0.4.4
  - threadpoolctl=2.1.0
  - three-merge=0.1.1
  - tk=8.6.10
  - toml=0.10.1
  - toolz=0.11.1
  - tornado=6.1
  - tqdm=4.56.0
  - traitlets=5.0.5
  - typed-ast=1.4.2
  - typing_extensions=3.7.4.3
  - ujson=4.0.2
  - unicodecsv=0.14.1
  - urllib3=1.26.3
  - watchdog=0.10.4
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - werkzeug=1.0.1
  - wheel=0.36.2
  - widgetsnbextension=3.5.1
  - wrapt=1.11.2
  - xlrd=2.0.1
  - xlsxwriter=1.3.7
  - xlwt=1.3.0
  - xmltodict=0.12.0
  - xz=5.2.5
  - yaml=0.2.5
  - yapf=0.30.0
  - zeromq=4.3.3
  - zfp=0.5.5
  - zict=2.0.0
  - zipp=3.4.0
  - zlib=1.2.11
  - zope=1.0
  - zope.event=4.5.0
  - zope.interface=5.2.0
  - zstd=1.4.5
  - jupyter-offlinenotebook=0.2.1
  
prefix: C:\Users\kolbi\Anaconda3
